name: digital_sobol_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  #Auth with SMS
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  #Compare objects
  equatable: ^2.0.5
  #Widgets
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  #Pick images
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Lints
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/SF-Pro-Display/
    - assets/icons/
  fonts:
    - family: SF-Pro-Display-Black
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
          weight: 400